name: Run R script every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.x'

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("your_package_name")'

      - name: Run R script
        run: |
          Rscript inv.R
